#define MAIN_OVERMAP_OBJECT_ID "home"
#define AWAY_OVERMAP_OBJECT_ID_LAVALAND "away"

#define OVERMAP_OBJECT_VISIBLE_STATION		(1<<1)
#define OVERMAP_OBJECT_VISIBLE_SYNDICATE	(1<<2)
#define OVERMAP_OBJECT_VISIBLE				(~0)
